**Py-Torch Library functions for Linear Regression**

In [9]:
import numpy as np
import torch
import torch.nn as nn

input = np.array([[75, 72, 40], 
                    [100, 89, 68], 
                    [85, 120, 62], 
                    [95, 55, 39], 
                    [65, 90, 75], 
                    [83, 72, 56], 
                    [81, 88, 75], 
                    [78, 114, 99], 
                    [98, 51, 57], 
                    [69, 96, 71], 
                    [79, 76, 54], 
                    [72, 77, 84], 
                    [67, 125, 67], 
                    [100, 53, 46], 
                    [70, 107, 60]], dtype='float32')

targets = np.array([[54, 75], 
                    [79, 121], 
                    [105, 130], 
                    [33, 39], 
                    [101, 110],
                    [45, 79], 
                    [85, 92], 
                    [110, 122], 
                    [36, 35], 
                    [95, 114], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], dtype='float32')

In [10]:
input = torch.from_numpy(input)
targets = torch.from_numpy(targets)

In [11]:
from torch.utils.data import TensorDataset

training_ds = TensorDataset(input, targets)
training_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [12]:
from torch.utils.data import DataLoader

batch_size = 5
train_dl = DataLoader(training_ds, batch_size, shuffle=True)
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [ 56.,  70.],
        [119., 133.],
        [ 81., 101.]])


In [13]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5624, -0.4961, -0.4894],
        [ 0.4171, -0.3244,  0.3972]], requires_grad=True)
Parameter containing:
tensor([ 0.4616, -0.3041], requires_grad=True)


In [15]:
list(model.parameters())
pred = model(input)
print(pred)

tensor([[ -94.8775,   25.4859],
        [-125.6966,   34.5213],
        [-143.3317,   15.5463],
        [ -96.3437,   42.9847],
        [-120.2294,   25.1329]], grad_fn=<AddmmBackward0>)


**Loss Function**

In [16]:
import torch.nn.functional as F

loss_fn = F.mse_loss

loss = loss_fn(model(input), targets)
print(loss)

tensor(22718.5098, grad_fn=<MseLossBackward0>)


**Optimizer**

In [17]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

**For Multiple Epochs**

In [18]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [20]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 207.3150
Epoch [20/100], Loss: 183.9913
Epoch [30/100], Loss: 163.4258
Epoch [40/100], Loss: 145.2899
Epoch [50/100], Loss: 129.2942
Epoch [60/100], Loss: 115.1836
Epoch [70/100], Loss: 102.7337
Epoch [80/100], Loss: 91.7466
Epoch [90/100], Loss: 82.0483
Epoch [100/100], Loss: 73.4854


In [21]:
pred = model(input)
print(pred)
print(targets)

tensor([[ 59.4925,  73.3059],
        [ 80.4935, 101.6769],
        [118.8497, 125.8500],
        [ 33.8213,  54.6277],
        [ 91.5977, 110.5511]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [22]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[56.0709, 71.5749]], grad_fn=<AddmmBackward0>)