In [3]:
import numpy as np
import torch

In [4]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [5]:
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

In [6]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [7]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [8]:
torch.matmul(inputs,weight.t()) + bias

def model(inputs):
    return inputs @ weight.t() + bias

In [9]:
pred = model(inputs)
print(pred)

tensor([[ -60.1510,   90.5661],
        [ -67.9705,  110.9919],
        [-123.7538,  128.0062],
        [ -54.5909,  113.9151],
        [ -59.2459,   88.5078]], grad_fn=<AddBackward0>)


**LOSS FUNCTION**

In [10]:
df0 = pred - targets
torch.sum(df0 * df0) / df0.numel()

tensor(13763.6406, grad_fn=<DivBackward0>)

In [11]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [12]:
loss = mse(pred, targets)
print(loss)

tensor(13763.6406, grad_fn=<DivBackward0>)


**Computing Gradients**

In [13]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[-12432.4307, -14457.9082,  -8559.8789],
        [  2882.3025,   1744.6296,   1262.9183]])
tensor([-149.3424,   30.1974])


**Train model using gradient descent**

In [14]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [15]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(9666.8301, grad_fn=<DivBackward0>)


In [16]:
for i in range(200):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [17]:
pred = model(inputs)
loss = mse(pred, targets)
print(loss)
print(pred)
print(targets)



tensor(170.1423, grad_fn=<DivBackward0>)
tensor([[ 58.9700,  61.1459],
        [ 90.6384,  78.3749],
        [ 96.6153, 121.0083],
        [ 32.3761,  43.6219],
        [109.9815,  82.0880]], grad_fn=<AddBackward0>)
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
