In [100]:
import numpy as np
import torch

In [101]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [102]:
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

In [103]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [104]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [105]:
inputs @ weight.t() + bias

def model(inputs):
    return inputs @ weight.t() + bias

In [106]:
pred = model(inputs)
print(pred)

tensor([[151.2644, 186.5215],
        [187.0975, 255.2035],
        [229.5560, 285.9214],
        [174.6937, 170.9047],
        [158.5029, 259.8927]], grad_fn=<AddBackward0>)


**LOSS FUNCTION**

In [107]:
df0 = pred - targets
torch.sum(df0 * df0) / df0.numel()

tensor(18098.3965, grad_fn=<DivBackward0>)

In [108]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [109]:
loss = mse(pred, targets)
print(loss)

tensor(18098.3965, grad_fn=<DivBackward0>)


**Computing Gradients**

In [110]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[ 9126.4004,  8485.5820,  5366.7451],
        [13183.3262, 13581.3848,  8586.9717]])
tensor([104.0229, 155.4888])


**Train model using gradient descent**

In [111]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [112]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(12488.0059, grad_fn=<DivBackward0>)


In [115]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [116]:
pred = model(inputs)
loss = mse(pred, targets)
print(loss)
print(pred)
print(targets)



tensor(160.8161, grad_fn=<DivBackward0>)
tensor([[ 61.4160,  58.1145],
        [ 75.6257,  87.3745],
        [126.8270, 105.4159],
        [ 44.8035,  26.5304],
        [ 76.6346, 107.8369]], grad_fn=<AddBackward0>)
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
