In [2]:
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB,GaussianNB
import numpy as np
import pandas as pd

dataset = pd.read_csv('Dataset3.csv')
print(dataset)
lbl_enc = preprocessing.LabelEncoder()

   Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0


In [3]:
feature=dataset.iloc[:,:-1].values
Class=dataset.iloc[:,-1].values

feature[ : ,0] = le.fit_transform(feature[ : ,0])
feature[ : ,1] = le.fit_transform(feature[ : ,2])
feature[ : ,2] = le.fit_transform(feature[ : ,2])

print(feature)
print(Class)

[[1 0 0 1]
 [1 1 1 2]
 [0 0 0 1]
 [1 0 0 1]
 [2 0 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 1]
 [0 0 0 0]
 [2 0 0 2]
 [1 1 1 2]
 [0 1 1 0]
 [0 0 0 1]
 [2 1 1 1]]
[0 0 1 1 1 0 1 0 1 1 0 1 1 0]


In [4]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(feature,Class, test_size = 0.05, random_state = 179)

In [7]:
from sklearn.naive_bayes import GaussianNB
gausn_NB= GaussianNB()
gausn_NB.fit(data_train, target_train)
target_pred = gausn_NB.predict(data_test)

In [8]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.0


In [9]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0. 0.]
recall: [0. 0.]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
q1= gausn_NB.predict([[1,2,0,1]])
print(q1)

[0]


In [12]:
q2= gausn_NB.predict([[2,0,1,2]])
print(q2)

[0]


**MultinomialNB**

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
data_train, data_test, target_train, target_test = train_test_split(feature,Class, test_size = 0.05, random_state = 179)
Multi_NB = MultinomialNB()
Multi_NB.fit(data_train,target_train)
target_pred = Multi_NB.predict(data_test)

confusion_matrix(target_test, target_pred)


array([[0, 0],
       [1, 0]])

In [17]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.0


In [18]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0. 0.]
recall: [0. 0.]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
p1 = Multi_NB.predict([[1,2,0,1]])
print(p1)

[0]


In [21]:
p2 = Multi_NB.predict([[2,0,1,2]])
print(p2)

[1]
