# **Implementation of Logistic Regression**

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
import math

In [47]:
dataset = pd.read_csv('BuyComputer.csv')
dataset.head()

User ID  Age  EstimatedSalary  Purchased
0  15624510   19            19000          0
1  15810944   35            20000          0
2  15668575   26            43000          0
3  15603246   27            57000          0
4  15804002   19            76000          0

In [48]:
sc = StandardScaler()
data = sc.fit_transform(dataset)
data

array([[-0.93657932, -1.78179743, -1.49004624, -0.74593581],
       [ 1.66838653, -0.25358736, -1.46068138, -0.74593581],
       [-0.32087714, -1.11320552, -0.78528968, -0.74593581],
       ...,
       [-0.52039175,  1.17910958, -1.46068138,  1.34059793],
       [ 0.88695546, -0.15807423, -1.07893824, -0.74593581],
       [-1.36231017,  1.08359645, -0.99084367,  1.34059793]])

In [49]:
X = data[:,0:2] # Excluding last column
Y = data[:,2]   # Last column as output label

In [50]:
Y = [0 if a<0 else 1 for a in Y]
Y = np.array(Y)

In [51]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 179)

In [52]:
class LogisticRegression:
  def sigmoid_func(self,X):
    return 1/(1+np.exp(-((X).dot(self.Weights)+self.Bias)))
  
  def __init__(self,lr,epochs=100):
    self.learning_rate = lr
    self.epochs = epochs
    pass
  
  def calculate_loss(self):
    return (np.sum(-1*(self.Y)*np.log(self.sigmoid_func(self.X))-(1-self.Y)*np.log(1-self.sigmoid_func(self.X)))/self.Num_samples)
  
  def fit(self,X,Y):
    
    # Assigning data to X and Y
    self.X = X
    self.Y = Y

    # Computing M -> No of training samples 
    # Computing N -> No of features
    self.Num_samples,self.Num_features = X.shape
    print(self.Num_samples,self.Num_features)

    # Initializing all the weights
    self.Weights = np.zeros(self.Num_features)
    self.Bias = 0
    for i in range(self.epochs):
      print("Epoch ",i)
      self.run_optimization()
      print(self.calculate_loss())
    return self

  def predict(self,X):
    ret_val = []
    for dat in self.sigmoid_func(X):
      ret_val.append(1 if dat>=0.5 else 0)
    return ret_val


  def run_optimization(self):
    ans = self.sigmoid_func(self.X)
    t = ( ans - self.Y.T )
    t = np.reshape( t, self.Num_samples ) 

    dW = np.dot( self.X.T, t ) / self.Num_samples
    db = np.sum( t ) / self.Num_samples
    

    self.Weights = self.Weights - self.learning_rate * dW    
    self.Bias = self.Bias - self.learning_rate * db

In [53]:
LR = LogisticRegression(0.1,400)
LR.fit(X_train,Y_train)

320 2
Epoch  0
0.6927398482260088
Epoch  1
0.6923532537880833
Epoch  2
0.6919863386130094
Epoch  3
0.691638097331013
Epoch  4
0.6913075753113759
Epoch  5
0.6909938662359751
Epoch  6
0.6906961097697304
Epoch  7
0.6904134893265923
Epoch  8
0.6901452299293581
Epoch  9
0.6898905961613124
Epoch  10
0.6896488902074616
Epoch  11
0.6894194499829484
Epoch  12
0.6892016473460846
Epoch  13
0.6889948863933407
Epoch  14
0.6887986018335504
Epoch  15
0.6886122574385454
Epoch  16
0.6884353445674117
Epoch  17
0.688267380761556
Epoch  18
0.6881079084077852
Epoch  19
0.6879564934666306
Epoch  20
0.6878127242631937
Epoch  21
0.6876762103378377
Epoch  22
0.6875465813541097
Epoch  23
0.6874234860613494
Epoch  24
0.6873065913095042
Epoch  25
0.6871955811137542
Epoch  26
0.6870901557666244
Epoch  27
0.6869900309953396
Epoch  28
0.6868949371622672
Epoch  29
0.6868046185063662
Epoch  30
0.6867188324236464
Epoch  31
0.6866373487847245
Epoch  32
0.6865599492876386
Epoch  33
0.686486426844168
Epoch  34
0.686416584

In [54]:
LR.Weights

array([0.17864073, 0.17697256])

In [55]:
def findScore(y_originals,y_pred):
  true = 0
  false = 0
  for i in range(len(y_pred)):
    if y_pred[i]==y_originals[i]:
      true = true + 1
    else:
      false = false + 1
  return true/(true+false)

In [56]:
y_pred = LR.predict(X_test)

In [57]:
print("Accuracy : ",findScore(Y_test,y_pred)*100)

Accuracy :  42.5


In [59]:
Y_test

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [60]:
np.array(y_pred)


array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])